---
- name: Brocade ICCX6450 Switch Post Staging
  hosts: icx6450s
  vars:
    username: ansible
    password: password
    tftpServer: "192.168.1.151"
    icx6450Bootrom: kxz10101.bin
    logfileDirectory: "/tmp/log"
  connection: local
  gather_facts: no

  tasks:
    - name: ICX6450--Generate SSH Key
      brocade_generate_ssh_key:
         host="{{ inventory_hostname }}"
         username="{{ username }}"
         password="{{ password }}"
         logfileDirectory="{{ logfileDirectory }}"
    - name: ICX6450--Copy Bootrom
      brocade_copy_bootrom:
         host="{{ inventory_hostname }}"
         username="{{ username }}"
         password="{{ password }}"
         bootrom="{{ icx6450Bootrom }}"
         tftpServer="{{ tftpServer }}"
         logfileDirectory="{{ logfileDirectory }}"
    - name: ICX6450--Copy Flash to Secondary
      brocade_copy_flash_secondary:
         host="{{ inventory_hostname }}"
         username="{{ username }}"
         password="{{ password }}"
         logfileDirectory="{{ logfileDirectory }}"

- name: Brocade ICCX6610 Switch Post Staging
  hosts: icx6610s
  vars:
    username: ansible
    password: password
    tftpServer: 192.168.1.151
    icx6610Bootrom: grz10100.bin
    logfileDirectory: "/tmp/log"
  connection: local
  gather_facts: no

  tasks:
    - name: ICX6610--Generate SSH Key
      brocade_generate_ssh_key:
         host="{{ inventory_hostname }}"
         username="{{ username }}"
         password="{{ password }}"
         logfileDirectory="{{ logfileDirectory }}"
    - name: ICX6610--Copy Bootrom
      brocade_copy_bootrom:
         host="{{ inventory_hostname }}"
         username="{{ username }}"
         password="{{ password }}"
         bootrom="{{ icx6610Bootrom }}"
         tftpServer="{{ tftpServer }}"
         logfileDirectory="{{ logfileDirectory }}"
    - name: ICX6610--Copy Flash to Secondary
      brocade_copy_flash_secondary:
         host="{{ inventory_hostname }}"
         username="{{ username }}"
         password="{{ password }}"
         logfileDirectory="{{ logfileDirectory }}"